// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NZWalks.API.Data;

#nullable disable

namespace NZWalks.API.Migrations
{
    [DbContext(typeof(NZWalksDbContext))]
    [Migration("20241227164327_Seeding Difficulty and Region")]
    partial class SeedingDifficultyandRegion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NZWalks.API.Models.Domain.Difficulty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Difficulties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("94e8d315-fecb-4f5a-9635-dc67bfaf0171"),
                            Name = "Easy"
                        },
                        new
                        {
                            Id = new Guid("fc18cd37-a3d9-4035-8eed-ab32928e7c53"),
                            Name = "Moderate"
                        },
                        new
                        {
                            Id = new Guid("0d21bba8-67a5-407f-8f7a-91d27d96eb49"),
                            Name = "Hard"
                        });
                });

            modelBuilder.Entity("NZWalks.API.Models.Domain.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9d8ac206-4b02-45ca-85ad-7642142bcda5"),
                            Code = "AUK",
                            Name = "Auckland",
                            RegionImageUrl = "https://www.doc.govt.nz/globalassets/images/conservation/nz-walks/north-island/auckland/auckland-region.jpg"
                        },
                        new
                        {
                            Id = new Guid("e743e16b-1035-49ad-a055-a5221f1a569e"),
                            Code = "WKO",
                            Name = "Waikato",
                            RegionImageUrl = "https://www.doc.govt.nz/globalassets/images/conservation/nz-walks/north-island/waikato/waikato-region.jpg"
                        },
                        new
                        {
                            Id = new Guid("815c05bd-8302-4f41-a714-0e1bb524dfbf"),
                            Code = "BOP",
                            Name = "Bay of Plenty",
                            RegionImageUrl = "https://www.doc.govt.nz/globalassets/images/conservation/nz-walks/north-island/bay-of-plenty/bay-of-plenty-region.jpg"
                        },
                        new
                        {
                            Id = new Guid("5006f660-2478-4fab-aa2c-10168ed81f0c"),
                            Code = "GIS",
                            Name = "Gisborne",
                            RegionImageUrl = "https://www.doc.govt.nz/globalassets/images/conservation/nz-walks/north-island/gisborne/gisborne-region.jpg"
                        },
                        new
                        {
                            Id = new Guid("04dbbc3e-26c3-4762-9b83-505596273903"),
                            Code = "HKB",
                            Name = "Hawke's Bay",
                            RegionImageUrl = "https://www.doc.govt.nz/globalassets/images/conservation/nz-walks/north-island/hawkes-bay/hawkes-bay-region.jpg"
                        });
                });

            modelBuilder.Entity("NZWalks.API.Models.Domain.Walk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DifficultyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("LengthInKm")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WalkImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("RegionId");

                    b.ToTable("Walks");
                });

            modelBuilder.Entity("NZWalks.API.Models.Domain.Walk", b =>
                {
                    b.HasOne("NZWalks.API.Models.Domain.Difficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NZWalks.API.Models.Domain.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("Region");
                });
#pragma warning restore 612, 618
        }
    }
}
